const USER_ROLES = require('./USER_ROLES');
const VEHICLE_STATUSES = require('./VEHICLE_STATUSES');
const VEHICLE_CATEGORIES = require('./VEHICLE_CATEGORIES');
const TRANSMISSION_TYPES = require('./TRANSMISSION_TYPES');

module.exports = {
    USER_ROLES,
    VEHICLE_STATUSES,
    VEHICLE_CATEGORIES,
    TRANSMISSION_TYPES
}