const USER_ROLES = require('./USER_ROLES');
const VEHICLE_STATUSES = require('./VEHICLE_STATUSES');
const VEHICLE_CATEGORIES = require('./VEHICLE_CATEGORIES');
const TRANSMISSION_TYPES = require('./TRANSMISSION_TYPES');
const EXAMINATION_TYPES = require('./EXAMINATION_TYPES');
const EXAM_LOCATIONS = require('./EXAM_LOCATIONS');

module.exports = {
    USER_ROLES,
    VEHICLE_STATUSES,
    VEHICLE_CATEGORIES,
    TRANSMISSION_TYPES,
    EXAMINATION_TYPES,
    EXAM_LOCATIONS
}